---
- name: Enable the http port on firewalld
  hosts: all
  
  tasks:
  
    - name: Enable HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
