---
- name: Setup MOTD on Linux Host
  hosts: all
  gather_facts: true
  tasks:
    - name: Copy over MOTD file
      template:
        src: motd.j2
        dest: /etc/motd
        mode: 0644
        owner: root
        group: root
